import { getAuthUserId } from '@/app/lib/auth';
import { sql } from '@/app/lib/db';

export async function POST(request: Request) {
  const userId = await getAuthUserId();
  if (!userId) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { month, year } = body;

    if (month === undefined || year === undefined) {
      return Response.json({ error: 'Missing month or year' }, { status: 400 });
    }

    // Get all recurring expenses grouped by category
    const recurringResult = await sql`
      SELECT e.category_id, c.name as category_name, SUM(e.amount) as total
      FROM expenses e
      JOIN expense_categories c ON c.id = e.category_id
      WHERE e.user_id = ${userId} AND e.is_recurring = 1
      GROUP BY e.category_id, c.name
    `;

    const created = [];
    let skipped = 0;

    for (const group of recurringResult.rows) {
      const { category_id, category_name, total } = group;
      const parsedTotal = parseFloat(total) || 0.0;

      // Check if envelope already exists for this category/month/year
      const existsResult = await sql`
        SELECT COUNT(*) as count 
        FROM envelopes 
        WHERE category_id = ${category_id} AND month = ${month} AND year = ${year} AND user_id = ${userId}
      `;
      const exists = parseInt(existsResult.rows[0].count) > 0;

      if (exists) {
        skipped++;
        continue;
      }

      const id = crypto.randomUUID();
      await sql`
        INSERT INTO envelopes (id, user_id, name, category_id, budgeted_amount, spent_amount, month, year, notes) 
        VALUES (${id}, ${userId}, ${category_name}, ${category_id}, ${parsedTotal}, 0.0, ${month}, ${year}, 'Auto-generated by Smart Envelope')
      `;

      const envResult = await sql`SELECT * FROM envelopes WHERE id = ${id}`;
      created.push({
        ...envResult.rows[0],
        budgeted_amount: parsedTotal,
        spent_amount: 0.0
      });
    }

    return Response.json({ created, skipped });
  } catch (error) {
    console.error('POST /api/envelopes/smart error:', error);
    return Response.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
